name: New Release
on:
  push:
    branches:
      - main
jobs:
  semantic_release:
    runs-on: ubuntu-latest
    name: Runs semantic release
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: release # Need an `id` for output variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: 000000000000000
          GIT_AUTHOR_NAME: danellecline
          GIT_COMMITTER_NAME: danellecline
        with:
          extra_plugins: |
            commitizen
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/exec
            @semantic-release/changelog
            @semantic-release/npm
            @semantic-release/git