name: New Release
on:
  push:
    branches:
      - main
jobs:
  semantic_release:
    runs-on: ubuntu-latest
    name: Runs semantic release
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: release # Need an `id` for output variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: 000000000000000
          GIT_AUTHOR_NAME: danellecline
          GIT_COMMITTER_NAME: danellecline
        with:
          extra_plugins: |
            commitizen
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/exec
            @semantic-release/changelog
            @semantic-release/npm
            @semantic-release/git
  pypi_release:
    name: Builds Using Poetry and Publishes to PyPI
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Add Poetry to path
        run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
      - run: poetry install
      - run: SAGEMAKER_ROLE=${{ secrets.SAGEMAKER_ROLE }} poetry run pytest
      - run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_TOKEN }}"
      - name: Publish package
        run: poetry publish --build
